### ISSUE TITLE
Frontend - Backend - DB architecture

### ISSUE THREAD

**Issue by gauchm** [gwf-uwaterloo/cuizinart#18]
Given we now have a proposed DB schema (#9), here's the (high-level) overview on how we plan to integrate the database into the front- and backend:

Fairly straightforward. Use Flask-SQLAlchemy for object-relational mapping. The backend can then load products/variables/domains and pass on to the frontend for display.

![cuizinart-architecture](https://user-images.githubusercontent.com/15731649/52882139-bf5b4180-3134-11e9-9627-28741384eedb.jpg)

**Comment by lintool** [comment]
1. Frontend (react) - is that itself a service or purely client-side (i.e., in browser)? Can you sketch that out? While you're at it, draw the browser and its connection to open street map APIs, etc.

2. For Graham, we deposit JSON query file in a known location and Graham cron job polls that location, right? Can you sketch this out a bit for clarity? I.e., "main" scp's over to Graham, etc.

3. For PySpark, it will have a query REST API itself? So that's another service? 

So (2) is a "scp" operation, while (3) is a REST call, right? Can you flesh that out?

**Comment by gauchm** [comment]
1. This is all client-side. I'm not into all details here, maybe @YIXIN-WANG can supply a sketch of this part?
2. Yes. Hopefully clarified in the new diagram below.
3. Currently, we have the PySpark job running within the "backend facade" app. I don't think that's a good design, because it doesn't allow running the facade without the PySpark service. 
Below is a basic proposal how we could separate the services: Create a separate flask app for PySpark which triggers the Spark jobs. In the future, we'll probably have to revisit this part and introduce some task queuing and (fair) scheduling for multi-user operation.

![cuizinart-architecture](https://user-images.githubusercontent.com/15731649/52902737-e6704c80-31e2-11e9-954f-1fcb7f6531fa.jpg)

**Comment by YIXIN-WANG** [comment]
As Martin said, it's purely client-side. The client-side code does not need to change much. The only difference is instead of reading Metadata files, our Flask server will read from the Metadata Database.
![image](https://user-images.githubusercontent.com/43051742/52903426-2804f580-31eb-11e9-92cb-e18917ac0a9b.png)

**Comment by gauchm** [comment]
Closing as with #72 we have architecture documentation in `docs/`
