### ISSUE TITLE
Frontend/backend integration

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/Cuizinart#2]
From #1 @gauchm 

> On a more general note, we should come up with a concept of how we deal with the two frontends for the Graham and PySpark backends. Do we keep them in one repo with two branches or should we spilt one off?

**Comment by lintool** [comment]
As a proposal, let's just use the JSON string by @julemai as the common interface?

We organize repo as:

```
+-+- frontend/
  |- backend-slurm/
  |- backend-pyspark/
```
It can be a config to select which backend we use?

**Comment by lintool** [comment]
Toward a unified frontend - use @julemai 's current JSON format as the query for both SLURM and PySpark backend.

The only difference then becomes how we "submit" the query - either scp to Graham for SLURM and post to a backend REST API for PySpark?

**Comment by gauchm** [comment]
Small detail: Actually we have a mini-REST API for Graham, too (it receives the JSON and scp's it to Graham)

**Comment by lintool** [comment]
@gauchm that makes it even cleaner... we have a backend facade, right?

**Comment by gauchm** [comment]
At the moment we don't have one explicitly, but that could be where we should go.

At least if we assume that the backends will not deviate far from each other in the future. If we expect to implement lots of fancy features in PySpark but keep the existing Graham backend, a common facade for query submission doesn't really make sense I think. (Because the Graham backend would not implement most of the facade's methods).
For loading the products into the UI (i.e. retrieving product metadata) however, we can have a common facade. (That's just one method though, so I'm not sure if that needs to be a facade explicitly)

**Comment by julemai** [comment]
Regarding the JSON strings that get sent over. The SLURM backend only checks if it contains keywords that it requires and ignores all other ones. So, you could include also PySpark-only relevant things. Wouldn't matter on my end.

**Comment by gauchm** [comment]
Done with #17.
