### ISSUE TITLE
Moving CaSPAr to cuizinart

### ISSUE THREAD

**Issue by lintool** [gwf-uwaterloo/cuizinart#63]
We need to move [CaSPAr](http://caspar-data.ca/) to the cuizinart backend.

**Comment by lintool** [comment]
@julemai We need to sort out a few issues:

+ What machine is http://caspar-data.ca/ currently being hosted on?
+ I assume CaSPAr should run on the same machine as the GWF instance? Just on a different port?

**Comment by julemai** [comment]
@lintool:
* Right now it is on a VM on ComputeCanada's EastCloud.
* It can run on the same as the GWF instance.
* I just would like to keep the starting page as it is right now (this is in the publication).
* The page that can be accessed via `-> Data Portal` would then be replaced with something that looks like the Cuizinart webpage but with CaSPAr logo, disclaimer, etc.

**Comment by lintool** [comment]
okay, sg.

**Comment by gauchm** [comment]
Some more notes here:
- Goal is to get CaSPAr off of its current proprietary ESRI frontend
- The new frontend should use the same codebase as Cuizinart but be a different instance

**Comment by gauchm** [comment]
Documenting some notes from discussion with @Alex-Weatherhead:
- The caspar-data.ca landing page will continue to exist, and the "Data Portal" link links to tuna. 
- Because we already have Cuizinart running on tuna, we need to distinguish the URLs. We do so by configuring the ngxinx server to route `tuna.cs.uwaterloo.ca/caspar` to the caspar docker container and `tuna.cs.uwaterloo.ca/cuizinart` to the cuizinart container.
- This should be a simple change in the `nginx.conf` file, changing `location / {...}` to `location /cuizinart {...}` and adding the same block for `location /caspar {...}`, just directing to a different port. 
- Once we're deploying this, we need to update the redirections from cuizinart.io/cuisinart.io to tuna.cs.uwaterloo.ca/cuizinart

**Comment by gauchm** [comment]
@raidraptor 
- [ ] Remove "CaSPAr Cuizinart" Title
- [ ] Replace USask logo with floodnet logo
- [ ] Change github logo to [CaSPAr](https://github.com/julemai/CaSPAr)
- [ ] Update About page
- [ ] Update email template
- [ ] Update information on variables based on the incoming JSON strings
- [ ] Only show variables with is_live = True
- [ ] Remove point selector from map

**Comment by gauchm** [comment]
From @julemai:

> We ask for more information when users register. We need that for reporting (to know where people are located and what their area of interest is). Maybe it is also the easiest to ask there for the Globus ID?! See attached screenshot. They also need to accept CaSPAr terms of Use and ECCC terms of Service. 

We'll have to update our DB schema for this (table `user`: add organization, areas of interest, proposal, one more terms of service field)

![grafik](https://user-images.githubusercontent.com/15731649/72562045-86fa4100-3878-11ea-845a-9a94f23a446b.png)

**Comment by julemai** [comment]
All done
